/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentform;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class Studinfo extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement pst;
       
    /**
     * Creates new form Studinfo
     */
    public Studinfo() {
        initComponents();
        connect();
    }
    void connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            JOptionPane.showMessageDialog(null,"Driver Loaded");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Driver Not Loaded");            
        }
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/studentinfo","root","");
            st=con.createStatement();
            JOptionPane.showMessageDialog(null,"Connected");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pBody = new javax.swing.JPanel();
        lStutentID = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lRoll = new javax.swing.JLabel();
        lStream = new javax.swing.JLabel();
        lYear = new javax.swing.JLabel();
        lCollegeName = new javax.swing.JLabel();
        textStudentID = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        textRoll = new javax.swing.JTextField();
        textStream = new javax.swing.JTextField();
        textYear = new javax.swing.JTextField();
        textCollegeName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bDelete = new javax.swing.JButton();
        bInsert = new javax.swing.JButton();
        bSearch = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        lStutentID1 = new javax.swing.JLabel();
        textStudentID1 = new javax.swing.JTextField();
        lName1 = new javax.swing.JLabel();
        textName1 = new javax.swing.JTextField();
        lRoll1 = new javax.swing.JLabel();
        textRoll1 = new javax.swing.JTextField();
        textCollegeName1 = new javax.swing.JTextField();
        textYear1 = new javax.swing.JTextField();
        textStream1 = new javax.swing.JTextField();
        lStream1 = new javax.swing.JLabel();
        lYear1 = new javax.swing.JLabel();
        lCollegeName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Student Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lStutentID.setText("Student ID");

        lName.setText("Name");

        lRoll.setText("Roll");

        lStream.setText("Stream");

        lYear.setText("Year");

        lCollegeName.setText("College Name");

        textStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStudentIDActionPerformed(evt);
            }
        });

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRollActionPerformed(evt);
            }
        });

        textStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreamActionPerformed(evt);
            }
        });

        textYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYearActionPerformed(evt);
            }
        });

        textCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCollegeNameActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        bDelete.setBackground(new java.awt.Color(51, 153, 0));
        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bInsert.setBackground(new java.awt.Color(0, 153, 51));
        bInsert.setText("INSERT");
        bInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertActionPerformed(evt);
            }
        });

        bSearch.setBackground(new java.awt.Color(51, 153, 0));
        bSearch.setText("SEARCH");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        bUpdate.setBackground(new java.awt.Color(102, 204, 0));
        bUpdate.setText("UPDATE");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bClear.setBackground(new java.awt.Color(51, 153, 0));
        bClear.setText("CLEAR");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        lStutentID1.setText("Student ID");

        textStudentID1.setEditable(false);
        textStudentID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStudentID1ActionPerformed(evt);
            }
        });

        lName1.setText("Name");

        textName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textName1ActionPerformed(evt);
            }
        });

        lRoll1.setText("Roll");

        textRoll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRoll1ActionPerformed(evt);
            }
        });

        textCollegeName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCollegeName1ActionPerformed(evt);
            }
        });

        textYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textYear1ActionPerformed(evt);
            }
        });

        textStream1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStream1ActionPerformed(evt);
            }
        });

        lStream1.setText("Stream");

        lYear1.setText("Year");

        lCollegeName1.setText("College Name");

        javax.swing.GroupLayout pBodyLayout = new javax.swing.GroupLayout(pBody);
        pBody.setLayout(pBodyLayout);
        pBodyLayout.setHorizontalGroup(
            pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBodyLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBodyLayout.createSequentialGroup()
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lRoll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lStutentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(textName)
                            .addComponent(textRoll))
                        .addGap(43, 43, 43)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pBodyLayout.createSequentialGroup()
                                .addComponent(lStream)
                                .addGap(124, 124, 124)
                                .addComponent(textStream, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBodyLayout.createSequentialGroup()
                                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lYear)
                                    .addComponent(lCollegeName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textYear, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(textCollegeName)))))
                    .addGroup(pBodyLayout.createSequentialGroup()
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pBodyLayout.createSequentialGroup()
                                .addComponent(bInsert)
                                .addGap(51, 51, 51)
                                .addComponent(bSearch)
                                .addGap(60, 60, 60)
                                .addComponent(bClear)
                                .addGap(53, 53, 53)
                                .addComponent(bUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lRoll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lStutentID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lCollegeName1)
                            .addComponent(lStream1)
                            .addComponent(lYear1))
                        .addGap(59, 59, 59)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textStudentID1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(textRoll1)
                            .addComponent(textName1)
                            .addComponent(textStream1)
                            .addComponent(textYear1)
                            .addComponent(textCollegeName1))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        pBodyLayout.setVerticalGroup(
            pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBodyLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStutentID)
                    .addComponent(lStream)
                    .addComponent(textStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(lYear)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRoll)
                    .addComponent(lCollegeName)
                    .addComponent(textRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBodyLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBodyLayout.createSequentialGroup()
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lStutentID1)
                            .addComponent(textStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lName1)
                            .addComponent(textName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lRoll1)
                            .addComponent(textRoll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lStream1)
                            .addComponent(textStream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lYear1)
                            .addComponent(textYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCollegeName1)
                            .addComponent(textCollegeName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDelete)
                    .addComponent(bUpdate)
                    .addGroup(pBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bInsert)
                        .addComponent(bSearch))
                    .addComponent(bClear))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStudentIDActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRollActionPerformed

    private void textStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStreamActionPerformed

    private void textYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYearActionPerformed

    private void textCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCollegeNameActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        try{
            st.execute("delete from tbl_student_info where id="+textStudentID1.getText());
            JOptionPane.showMessageDialog(null,"Deleted Successfully");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Unsuccessful");
        }          // TODO add your handling code here:
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertActionPerformed
        
        try{
            pst=con.prepareStatement("insert into tbl_student_info values(?,?,?,?,?,?)");
            pst.setString(1,textStudentID.getText());
            pst.setString(2,textName.getText());
            pst.setString(3,textRoll.getText());
            pst.setString(4,textStream.getText());
            pst.setString(5,textYear.getText());
            pst.setString(6,textCollegeName.getText());
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null,"Data Successfully Inserted");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Not Inserted");
        }
    }//GEN-LAST:event_bInsertActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        try{
            rs=st.executeQuery("select * from tbl_student_info");
            table.setModel(DbUtils.resultSetToTableModel(rs));
            JOptionPane.showMessageDialog(null,"Successful");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Can't Fetch Data");
        }
    }//GEN-LAST:event_bSearchActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        try{
            pst=con.prepareStatement("update tbl_student_info set name=?,roll=?,stream=?,year=?,college=? where id=?");
            pst.setString(6,textStudentID1.getText());
            pst.setString(1,textName1.getText());
            pst.setString(2,textRoll1.getText());
            pst.setString(3,textStream1.getText());
            pst.setString(4,textYear1.getText());
            pst.setString(5,textCollegeName1.getText());
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null,"Data Successfully Updated");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Not Updated");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        textStudentID1.setText("");
        textName1.setText("");
        textRoll1.setText("");
        textStream1.setText("");
        textYear1.setText("");
        textCollegeName1.setText("");
        textStudentID.setText("");
        textName.setText("");
        textRoll.setText("");
        textStream.setText("");
        textYear.setText("");
        textCollegeName.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void textStudentID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStudentID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStudentID1ActionPerformed

    private void textName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textName1ActionPerformed

    private void textRoll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRoll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRoll1ActionPerformed

    private void textCollegeName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCollegeName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCollegeName1ActionPerformed

    private void textYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textYear1ActionPerformed

    private void textStream1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textStream1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textStream1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int r=table.getSelectedRow();
        Object o=table.getValueAt(r,0);
        try{
            rs=st.executeQuery("select * from tbl_student_info where id="+o.toString());
            rs.next();
            textStudentID1.setText(rs.getString("id"));
            textName1.setText(rs.getString("Name"));
            textRoll1.setText(rs.getString("Roll"));
            textStream1.setText(rs.getString("Stream"));
            textYear1.setText(rs.getString("Year"));
            textCollegeName1.setText(rs.getString("College"));
            JOptionPane.showMessageDialog(null,"Data is placed");

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Can't Fetch Data");
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bInsert;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCollegeName;
    private javax.swing.JLabel lCollegeName1;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lName1;
    private javax.swing.JLabel lRoll;
    private javax.swing.JLabel lRoll1;
    private javax.swing.JLabel lStream;
    private javax.swing.JLabel lStream1;
    private javax.swing.JLabel lStutentID;
    private javax.swing.JLabel lStutentID1;
    private javax.swing.JLabel lYear;
    private javax.swing.JLabel lYear1;
    private javax.swing.JPanel pBody;
    private javax.swing.JTable table;
    private javax.swing.JTextField textCollegeName;
    private javax.swing.JTextField textCollegeName1;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textName1;
    private javax.swing.JTextField textRoll;
    private javax.swing.JTextField textRoll1;
    private javax.swing.JTextField textStream;
    private javax.swing.JTextField textStream1;
    private javax.swing.JTextField textStudentID;
    private javax.swing.JTextField textStudentID1;
    private javax.swing.JTextField textYear;
    private javax.swing.JTextField textYear1;
    // End of variables declaration//GEN-END:variables
}
